-- ─────────────────────────────────────────────
-- 16. love_type_labels 시드 — 보류
-- ─────────────────────────────────────────────
-- SCHEMA.md는 love_type_labels의 "테이블 구조"만 정의하며(§4-3), 36종 실제
-- 라벨 데이터(code, core_en/suffix_en 네이밍, label_ko, copy_ko, description_ko)는
-- 어디에도 원문으로 주어져 있지 않다. 예시로 등장하는 코드는 'KLE', 'MSF',
-- 'KEEL', 'MUSE' 등 2건뿐이며, 9개 애니어그램 코어 × 4개 애착유형을 36개
-- 코드/영문명으로 매핑하는 규칙 자체가 아직 확정되지 않았다.
--
-- docs/ONDOLOG_ROADMAP.md §5도 "36종 연애유형 상세 설명문(description_ko)"을
-- "Phase 3 전" 처리해야 할 미작성 콘텐츠로 명시하고 있다.
--
-- CLAUDE.md 원칙("문서에 없는 내용을 지어내지 말 것", "코너 생성 원칙: 원문
-- 우선, 없는 걸 지어내지 않는다")에 따라 이 마이그레이션에서 36종 라벨/카피를
-- 임의로 창작해 채우지 않는다. love_type_labels 테이블(004_personality.sql)과
-- RLS 정책(012_rls_policies.sql, 전체 공개 읽기)은 이미 준비되어 있으므로,
-- 콘텐츠팀이 코드 네이밍 규칙과 36종 카피를 확정하는 즉시 이 파일 자리에
-- INSERT 문을 채우면 된다.
--
-- 결정 기록: .claude/state/DECISIONS.md
-- 후속 조치 필요: .claude/state/HANDOFF.md (Phase 3 착수 전 콘텐츠 확정 필요)

-- (의도적으로 INSERT 없음 — 데이터 없이도 스키마/RLS는 유효하다)
